BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Trabajos` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ID_Coche`	INTEGER NOT NULL,
	`DNI_Empleado`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Repuestos` (
	`Nombre`	TEXT NOT NULL UNIQUE,
	`Uds_Disponibles`	INTEGER NOT NULL,
	`Uds_Empleadas`	INTEGER NOT NULL,
	`Precio_Ud`	INTEGER NOT NULL,
	PRIMARY KEY(`Nombre`)
);
CREATE TABLE IF NOT EXISTS `Facturas` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Horas`	REAL NOT NULL,
	`Num_Ventanas`	INTEGER,
	`Num_Puertas`	INTEGER,
	`Num_Ruedas`	INTEGER,
	`Num_Motores`	INTEGER,
	`ID_Trabajo`	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `Empleados` (
	`DNI`	TEXT NOT NULL UNIQUE,
	`Nombre`	TEXT NOT NULL,
	`Apellido1`	TEXT NOT NULL,
	`Apellido2`	TEXT NOT NULL,
	PRIMARY KEY(`DNI`)
);
CREATE TABLE IF NOT EXISTS `Clientes` (
	`DNI`	TEXT NOT NULL UNIQUE,
	`Nombre`	TEXT NOT NULL,
	`Apellido1`	TEXT NOT NULL,
	`Apellido2`	TEXT NOT NULL,
	`Telefono`	TEXT NOT NULL UNIQUE,
	`Direccion`	TEXT NOT NULL,
	PRIMARY KEY(`DNI`)
);

CREATE TABLE IF NOT EXISTS `Automoviles` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Marca`	TEXT NOT NULL,
	`Modelo`	TEXT NOT NULL,
	`Matricula`	TEXT NOT NULL,
	`DNI_Dueno`	TEXT NOT NULL
);

INSERT INTO `Clientes` VALUES ('48205347S','Fernando','Gonzalez','Ramos','610428122','c/polvoranca');
INSERT INTO `Clientes` VALUES ('48627981F','Paco','Perez','Abellan','230538117','c/mishuevos');

COMMIT;
